### ISSUE TITLE
Is it on pause?

### ISSUE THREAD

**Issue by nis-ship-it** [05nelsonm/kmp-tor#543]
@05nelsonm somehow landed up on this repo due an issue. Just curious enough i was recently following up ytuber who pointed out a book: Tower of Basel, why's ur profile pic of Agustín Carstens???

**Comment by 05nelsonm** [comment]
It is not on pause. [kmp-tor-resource](https://github.com/05nelsonm/kmp-tor-resource) needed a massive refactor to support `iOS` which took a while to get nailed down. Just have to adapt this repo to the new resource formats and connect things up here.

> why's ur profile pic of Agustín Carstens???

For a daily reminder of who the final boss is, in order to drive my autistic goals of helping others defeat him.
